name: Publish to Maven Central

on:
  push:
    tags:
      - 'v*'  # Triggers on tags like v1.0.0

jobs:
  publish:
    name: Publish release
    runs-on: ubuntu-latest
    environment: maven

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: gradle

      - name: Import GPG key
        run: echo "$GPG_PRIVATE_KEY" | gpg --batch --import
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Set up Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: Publish to Maven Central
        run: ./gradlew publish --no-daemon --stacktrace
        env:
          MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}